#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path
import runpy
import sys


def _is_colorbar_axis(ax) -> bool:
    return getattr(ax, "_colorbar", None) is not None or ax.get_label() == "<colorbar>"


def _remove_figure_title(fig) -> None:
    title = getattr(fig, "_suptitle", None)
    if title is not None:
        try:
            title.remove()
        except Exception:
            title.set_text("")
            title.set_visible(False)
        fig._suptitle = None


def _set_axis_fonts(ax, *, title=None, label=None, tick=None, legend=None) -> None:
    if title is not None:
        ax.title.set_fontsize(title)
    if label is not None:
        ax.xaxis.label.set_fontsize(label)
        ax.yaxis.label.set_fontsize(label)
    if tick is not None:
        ax.tick_params(axis="both", which="both", labelsize=tick)
    if legend is not None:
        leg = ax.get_legend()
        if leg is not None:
            texts = [txt for txt in leg.get_texts() if txt.get_text().strip()]
            if not texts:
                leg.remove()
            else:
                for txt in texts:
                    txt.set_fontsize(legend)
                title_obj = leg.get_title()
                if title_obj is not None:
                    title_obj.set_fontsize(legend)


def _set_colorbar_fonts(fig, *, label=None, tick=None) -> None:
    for ax in fig.axes:
        if not _is_colorbar_axis(ax):
            continue
        if label is not None:
            ax.xaxis.label.set_fontsize(label)
            ax.yaxis.label.set_fontsize(label)
        if tick is not None:
            ax.tick_params(axis="both", which="both", labelsize=tick)


def _set_vertical_spacing(fig, value: float) -> None:
    """Increase subplot separation without assuming a specific layout engine."""
    try:
        fig.set_constrained_layout_pads(h_pad=0.035, w_pad=0.025, hspace=value, wspace=0.08)
        return
    except Exception:
        pass
    try:
        fig.subplots_adjust(hspace=value)
    except Exception:
        pass


def _apply_reference_results_format(fig, filename: str) -> None:
    """Final paper-format tweaks for Results figures generated by the OOP tools.

    The numerical post-processing routines are left untouched.  Only matplotlib
    artists are adjusted immediately before savefig, so rerunning this wrapper
    changes presentation but never the stored CFD/statistical data.
    """
    name = Path(filename).name
    normal_axes = [ax for ax in fig.axes if not _is_colorbar_axis(ax)]

    # Fig. 5.3 -- detailed Mt=0.25 time histories.
    if name in {"hit2d_history.png", "time_history.png"}:
        _remove_figure_title(fig)
        for ax in normal_axes:
            _set_axis_fonts(ax, title=15, label=13, tick=11, legend=11)
            xlabel = ax.get_xlabel()
            if "eddy" in xlabel.lower() or "turnover" in xlabel.lower() or "rms" in xlabel.lower():
                ax.set_xlabel(r"$N_{\mathrm{eddy}}$", fontsize=13)
        _set_vertical_spacing(fig, 0.10)
        return

    # Fig. 5.4 -- instantaneous physical fields.  The colorbar is effectively
    # the legend for each field, so its text is enlarged together with the axes.
    if name in {"physics_fields_final.png", "hit2d_physics_fields.png"}:
        for ax in normal_axes:
            _set_axis_fonts(ax, title=16, label=15, tick=13, legend=13)
        _set_colorbar_fonts(fig, label=14, tick=12)
        title = getattr(fig, "_suptitle", None)
        if title is not None:
            title.set_fontsize(16)
        return

    # Fig. 5.5 -- spectral diagnostics: only reduce the two panel titles.
    if name == "energy_enstrophy_spectra.png":
        for ax in normal_axes:
            _set_axis_fonts(ax, title=18)
        return

    # Fig. 5.6 -- one-point PDFs: remove the redundant overall title and make
    # the four panel titles less dominant.  All other typography is preserved.
    if name == "one_point_pdfs.png":
        _remove_figure_title(fig)
        for ax in normal_axes:
            _set_axis_fonts(ax, title=18)
        return

    # Fig. 5.7 -- temporal anisotropy diagnostics.  Smaller typography and a
    # short turnover-count label give more room to the data panels.
    if name == "component_energy_anisotropy.png":
        for ax in normal_axes:
            _set_axis_fonts(ax, title=15, label=14, tick=12, legend=11)
            xlabel = ax.get_xlabel()
            if xlabel.strip():
                ax.set_xlabel(r"$N_{\mathrm{eddy}}$", fontsize=14)
        _set_vertical_spacing(fig, 0.16)
        return

    # Fig. 5.8 -- two-point correlations.  The horizontal coordinate is the
    # separation r (not turnover count), so it is deliberately kept as r.
    if name == "directional_isotropy_correlations.png":
        for ax in normal_axes:
            _set_axis_fonts(ax, title=15, label=14, tick=12, legend=11)
        _set_vertical_spacing(fig, 0.16)
        return


def _install_savefig_hook(profile: str) -> None:
    if profile == "none":
        return

    from matplotlib.figure import Figure

    original_savefig = Figure.savefig

    def styled_savefig(self, fname, *args, **kwargs):
        if profile == "reference-results":
            _apply_reference_results_format(self, str(fname))
        return original_savefig(self, fname, *args, **kwargs)

    Figure.savefig = styled_savefig


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("--base", type=float, default=17)
    parser.add_argument("--title", type=float, default=19)
    parser.add_argument("--label", type=float, default=18)
    parser.add_argument("--tick", type=float, default=15)
    parser.add_argument("--legend", type=float, default=15)
    parser.add_argument("--suptitle", type=float, default=21)
    parser.add_argument("--annotation", type=float, default=13)
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument(
        "--figure-profile",
        choices=("none", "reference-results"),
        default="none",
        help="Optional figure-specific paper-layout tweaks applied immediately before savefig.",
    )

    parser.add_argument("script")
    parser.add_argument("script_args", nargs=argparse.REMAINDER)

    args = parser.parse_args()

    repo = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(repo))

    from OOP.postprocess.thesis_plot_style import (
        ThesisPlotStyle,
        apply_thesis_style,
    )

    apply_thesis_style(
        ThesisPlotStyle(
            base=args.base,
            axes_title=args.title,
            axes_label=args.label,
            ticks=args.tick,
            legend=args.legend,
            figure_title=args.suptitle,
            colorbar_label=args.label,
            annotation=args.annotation,
            min_dpi=args.dpi,
        )
    )

    _install_savefig_hook(args.figure_profile)

    script = Path(args.script)
    if not script.is_absolute():
        script = repo / script

    if not script.exists():
        raise FileNotFoundError(f"Plotting script not found: {script}")

    forwarded = args.script_args
    if forwarded[:1] == ["--"]:
        forwarded = forwarded[1:]

    sys.argv = [str(script), *forwarded]

    runpy.run_path(
        str(script),
        run_name="__main__",
    )


if __name__ == "__main__":
    main()
